### GET ALL MOVIES
GET http://localhost:8081/api/movies

### GET MOVIE BY ID
GET http://localhost:8081/api/movies/c9e31d60-9823-4436-a848-aab138133294

### DELETE MOVIE BY ID
DELETE http://localhost:8081/api/movies/c9e31d60-9823-4436-a848-aab138133294

### GET MOVIE BY STUDIO ID
GET http://localhost:8081/api/studios/91848afd-fa39-425b-b23b-3f0547fabed1/movies

### CREATE MOVIE
PUT http://localhost:8081/api/movies/91848afd-fa39-425b-b23b-3f0547fbeda1
Content-Type: application/json

{
  "title": "Testowy Film",
  "director": "Testowy Dyrektor",
  "publisher": "Testowy wydawca",
  "yearOfPublication": 2005,
  "studio": "0a19e12d-0ce4-444e-bff1-86714189ea13"
}


### DELETE STUDIOS
DELETE http://localhost:8080/api/studios/daf676a1-28f9-4212-874e-4b5fdabc4c24

